/**
 * Admin Log Action 상수 정의
 * adminLogs 컬렉션의 action 필드에 사용
 */
const ADMIN_LOG_ACTIONS = {
    // 사용자 관련
    USER_REGISTERED: "USER_REGISTERED",
    USER_LOGIN: "USER_LOGIN",
    USER_LOGOUT: "USER_LOGOUT",
    USER_PROFILE_UPDATE: "USER_PROFILE_UPDATE",
    USER_DELETED: "USER_DELETED",
  
    // 커뮤니티/게시글 관련
    COMMUNITY_CREATED: "COMMUNITY_CREATED",
    COMMUNITY_UPDATED: "COMMUNITY_UPDATED",
    COMMUNITY_DELETED: "COMMUNITY_DELETED",
    POST_CREATED: "POST_CREATED",
    POST_UPDATED: "POST_UPDATED",
    POST_DELETED: "POST_DELETED",
    POST_LOCKED: "POST_LOCKED",
    POST_UNLOCKED: "POST_UNLOCKED",
  
    // 댓글/리액션 관련
    COMMENT_CREATED: "COMMENT_CREATED",
    COMMENT_UPDATED: "COMMENT_UPDATED",
    COMMENT_DELETED: "COMMENT_DELETED",
    REACTION_ADDED: "REACTION_ADDED",
    REACTION_REMOVED: "REACTION_REMOVED",
  
    // 이벤트/공지 관련
    ANNOUNCEMENT_CREATED: "ANNOUNCEMENT_CREATED",
    ANNOUNCEMENT_UPDATED: "ANNOUNCEMENT_UPDATED",
    ANNOUNCEMENT_DELETED: "ANNOUNCEMENT_DELETED",
    EVENT_CREATED: "EVENT_CREATED",
    EVENT_UPDATED: "EVENT_UPDATED",
    EVENT_DELETED: "EVENT_DELETED",
    EVENT_PARTICIPATED: "EVENT_PARTICIPATED",
  
    // 관리자/제재 관련
    USER_BANNED: "USER_BANNED",
    USER_UNBANNED: "USER_UNBANNED",
    REPORT_HANDLED: "REPORT_HANDLED",
    POST_REPORTED: "POST_REPORTED",
    COMMENT_REPORTED: "COMMENT_REPORTED",
  
    // 포인트/보상 관련
    REWARD_GRANTED: "REWARD_GRANTED",
    REWARD_REVOKED: "REWARD_REVOKED",
    POINTS_ADDED: "POINTS_ADDED",
    POINTS_DEDUCTED: "POINTS_DEDUCTED",
  
    // 동기화 일반
    SYNC_STARTED: "SYNC_STARTED",
    SYNC_COMPLETED: "SYNC_COMPLETED",
    SYNC_FAILED: "SYNC_FAILED",
    SYNC_CONFLICT_DETECTED: "SYNC_CONFLICT_DETECTED",
    SYNC_RESOLVED: "SYNC_RESOLVED",
  
    // 데이터별 세분화
    USER_SYNCED: "USER_SYNCED",
    USER_ALL_SYNCED: "USER_ALL_SYNCED",
    USER_PART_SYNCED: "USER_PART_SYNCED", //부분 데이터 불러오기
    USER_SYNC_FAILED: "USER_SYNC_FAILED",
    COMMUNITY_SYNCED: "COMMUNITY_SYNCED",
    POST_SYNCED: "POST_SYNCED",
    COMMENT_SYNCED: "COMMENT_SYNCED",
    REWARD_SYNCED: "REWARD_SYNCED",
  
    // 외부 서비스 기준
    FIREBASE_SYNC_STARTED: "FIREBASE_SYNC_STARTED",
    FIREBASE_SYNC_COMPLETED: "FIREBASE_SYNC_COMPLETED",
    NOTION_SYNC_STARTED: "NOTION_SYNC_STARTED",
    NOTION_SYNC_COMPLETED: "NOTION_SYNC_COMPLETED",
    NOTION_ALL_SYNC_COMPLETED: "NOTION_ALL_SYNC_COMPLETED",
    NOTION_PART_SYNC_COMPLETED: "NOTION_PART_SYNC_COMPLETED",
    NOTION_SYNC_FAILED: "NOTION_SYNC_FAILED",

    // 백업 관련
    NOTION_BACKUP_COMPLETED: "NOTION_BACKUP_COMPLETED", //노션 백업 성공
    NOTION_BACKUP_FAILED: "NOTION_BACKUP_FAILED", //노션 백업 실패




    //신규 사용하는 액션로그(실제 사용)
    NOTION_PARTIAL_BACKUP_COMPLETED: "NOTION_PARTIAL_BACKUP_COMPLETED", // 노션 부분 데이터 백업 성공
    NOTION_PARTIAL_BACKUP_FAILED: "NOTION_PARTIAL_BACKUP_FAILED",     // 노션 부분 데이터 백업 실패
    
    NOTION_FULL_BACKUP_COMPLETED: "NOTION_FULL_BACKUP_COMPLETED", // 노션 전체 데이터 백업 성공
    NOTION_FULL_BACKUP_FAILED: "NOTION_FULL_BACKUP_FAILED",     // 노션 전체 데이터 백업 실패
    
    NOTION_USER_FULL_SYNCED: "NOTION_USER_FULL_SYNCED", // 노션 전체 사용자 동기화 성공
    NOTION_USER_PARTIAL_SYNCED: "NOTION_USER_PARTIAL_SYNCED", //부분 데이터 불러오기  
    
    ADMIN_LOG_MEMBER_SYNC_N2F_SELECTED: "ADMIN_LOG_MEMBER_SYNC_N2F_SELECTED", // 회원관리 노션 데이터베이스에서 선택된 데이터 -> Firebase 동기화

    NOTION_USER_RESTORE_REQUESTED: "NOTION_USER_RESTORE_REQUESTED", // 노션 회원관리 복원 요청 (복원 버튼 클릭)

    NOTION_REPORT_PROCESS_REQUESTED: "NOTION_REPORT_PROCESS_REQUESTED", // 노션 신고 콘텐츠 처리 요청 (관리자 액션)
    
  };
  
  module.exports = {
    ADMIN_LOG_ACTIONS,
  };