const USER_MISSIONS_COLLECTION = "userMissions";
const USER_MISSION_STATS_COLLECTION = "userMissionStats";
const MISSION_POSTS_COLLECTION = "missionPosts";
const MISSION_LAST_RESET_COLLECTION = "missionDailyResets";
const MISSION_LIKES_COLLECTION = "missionLikes";
const MISSION_LIKES_STATS_COLLECTION = "missionLikesStats";

const MISSION_STATUS = {
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  QUIT: "QUIT",
};

const BLOCKED_STATUSES = [MISSION_STATUS.IN_PROGRESS, MISSION_STATUS.COMPLETED];

const MAX_ACTIVE_MISSIONS = 3;
const FIRST_MISSION_REWARD_LIMIT = 3; // 최초 미션 리워드 지급 횟수 (튜토리얼 단계)

module.exports = {
  USER_MISSIONS_COLLECTION,
  USER_MISSION_STATS_COLLECTION,
  MISSION_POSTS_COLLECTION,
  MISSION_LAST_RESET_COLLECTION,
  MISSION_LIKES_COLLECTION,
  MISSION_LIKES_STATS_COLLECTION,
  MISSION_STATUS,
  BLOCKED_STATUSES,
  MAX_ACTIVE_MISSIONS,
  FIRST_MISSION_REWARD_LIMIT,
};

